services:

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'armonia_e_rispetto'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s

  flyway:
    image: redgate/flyway
    restart: "no"
    container_name: flyway
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../db/migrations:/flyway/sql
    command: -url=jdbc:mysql://mysql:3306/armonia_e_rispetto -user=root -password=root migrate

  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface port